name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04  # latest version where Python 3.6 is available
    strategy:
      fail-fast: false
      matrix:
        include:
          # The Ubuntu 18.04 image will be removed from GitHub in April 2023,
          # at that time we will need to migrate tests to ubuntu-20.04 even if
          # our actual production environment is still Ubuntu 18.04.
          - os: ubuntu-18.04
            python-version: 3.6
          - os: ubuntu-20.04
            python-version: 3.8
          # This is known to be broken because the dependency versions pinned
          # by piptools under Python 3.6 are too old for 3.10. Until a fix is
          # found, there is no use running these tests.
          # - os: ubuntu-22.04
          #   python-version: 3.10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: PIP cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-python${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        tox
